M48
; DRILL file {KiCad 7.0.10} date Sunday, February 04, 2024 at 10:18:42 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-04T22:18:42-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X3.767Y-4.5004
T2
X4.4059Y-3.25
X4.4059Y-4.45
X5.2059Y-3.25
X5.2059Y-4.45
M30
